### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by TGZ12345** [guidoAI/monocular_distance#7]
Hello! I've been reading a recent article of yours entitled "Monotonic Distance Estimation with optical flow maneuver and efference copies: a-based strategy, " but I've downloaded your code and run it, and come up with a result that doesn't match the one in the paper

**Comment by guidoAI** [comment]
Hi, great that you're interested in the paper and results!

Can you be more specific about what you tried and what did not work?

**Comment by TGZ12345** [comment]
> Hi, great that you're interested in the paper and results!
> 
> Can you be more specific about what you tried and what did not work?

The code mentioned in your paper does not compile the results of chapter 4. Would you like to share the detailed simulation code of chapters 4 and 5.Thank you.

**Comment by guidoAI** [comment]
Dear TGZ,

can you be even more specific than that? MATLAB code does not "compile" - it is a scripting language. You're not talking about the real-world experiments in section 6, right?

I just downloaded the repo and when I run demo.m, all the plots work. For instance, this is the result of the landing on the edge of oscillation, showing the relation between height and the control gain:
![image](https://user-images.githubusercontent.com/4037738/86734637-6d210600-c032-11ea-82ed-c7c07a0d532f.png)

Of course, Figure 9 looks slightly nicer, as there are multiple runs, the initial locations are red, and there is a color coding related to the gain. To be honest, I do not know where the nice plotting script is, but you can (easily?) make this yourself, by running the function multiple times and changing the plotting colors, etc.

I get no errors. If you can send me the exact command that does not work for you, and if you can tell me what simulation result you're trying to reproduce, then I can help you further.

Kind regards,

Guido.

**Comment by TGZ12345** [comment]
Thank you for your patience






---Original---
