### ISSUE TITLE
Comment  Neural Networks using fast transforms

### ISSUE THREAD

**Issue by ghost** [guidoAI/monocular_distance#8]
You know you can make neural networks using fast transforms.  In the matrix view of a fast transform it is a fixed system of weights.  Which would give you a frozen neural network if used.  The simple observation then is to use it with adjustable (parametric) activation functions.  If you use the fast Walsh Hadamard transform the cost per layer of width n is:

- nlog2(n) add subtract operations
- n multiplies
- n switching decisions
- 2n parameters

That's low isn't it?
[https://ai462qqq.blogspot.com/](url)
[https://siobhan10.github.io/WHT/](url)

**Comment by guidoAI** [comment]
This repo doesn't use networks. So I guess this is not related?
